# Use Arch to test build outside of Ubuntu/Pop.
#
# Tests with recent version of dependencies. Another testson a different
# distro could be used to test for lowest supported.
#
# A minimal image should also help to confirm what dependencies are needed.

name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: '0 7 * * *' # Midnight MST daily

jobs:
  Test:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      volumes:
        - /:/host
    steps:
    - run: >
        pacman --noconfirm --needed -Syu
        cargo
        clang
        desktop-file-utils
        git
        gtk3
        gtk4
        just
        libdisplay-info
        libinput
        libxkbcommon
        llvm
        mesa
        meson
        pipewire
        pulseaudio
        seatd
        wayland
        lld
        expat
        fontconfig
        freetype2
        flatpak
        nasm
    - run: rm -rf /host/usr/local/lib/android # Free space
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    # Safe directory behavior seems to have issues with `container:`
    # https://github.com/actions/checkout/issues/915
    - run: git config --global --add safe.directory '*'
    - run: just sysext
